<?php

/**
 * Generate the Unicode Line_Break lookup tables used by the UAX #14 line breaker
 * in every language port (PHP, Go, Rust, TypeScript).
 *
 * Usage:
 *   php tools/generate-linebreak-data.php [UNICODE_VERSION] [UCD_DIR]
 *
 * Reads LineBreak.txt, EastAsianWidth.txt, UnicodeData.txt and emoji-data.txt
 * from UCD_DIR, downloading them from unicode.org when UCD_DIR is omitted.
 *
 * Each table entry is one byte:
 *   bits 0-5  resolved Line_Break class (see CLASSES; LB1 applied except SA)
 *   bit 6     East_Asian_Width is F, W or H (the $EastAsian set of LB19a/LB30)
 *   bit 7     Extended_Pictographic and unassigned (LB30b)
 *
 * License: Apache-2.0
 */

declare(strict_types=1);

const CLASSES = [
    'AL', 'BK', 'CR', 'LF', 'NL', 'SP', 'ZW', 'WJ', 'GL', 'CL', 'CP', 'EX', 'IS', 'SY',
    'OP', 'QU', 'QI', 'QF', 'NS', 'B2', 'BA', 'BB', 'HY', 'HH', 'CB', 'IN', 'HL', 'NU',
    'PR', 'PO', 'ID', 'EB', 'EM', 'H2', 'H3', 'JL', 'JV', 'JT', 'RI', 'ZWJ', 'CM',
    'AK', 'AP', 'AS', 'VF', 'VI', 'SA', 'SM',
];
const FLAG_EAST_ASIAN = 0x40;
const FLAG_EXT_PICT_UNASSIGNED = 0x80;
const MAX_CP = 0x10FFFF;

$version = $argv[1] ?? '16.0.0';
$ucdDir  = $argv[2] ?? null;

function ucdFile(string $name, string $version, ?string $dir): string
{
    if ($dir !== null) {
        return file_get_contents($dir . '/' . basename($name)) ?: throw new RuntimeException("Cannot read $name");
    }
    $url = "https://www.unicode.org/Public/$version/ucd/$name";
    fwrite(STDERR, "Downloading $url\n");
    return file_get_contents($url) ?: throw new RuntimeException("Cannot download $url");
}

/** Parse "XXXX..YYYY ; value" property files into a per-code-point callback. */
function eachRange(string $data, callable $fn): void
{
    foreach (explode("\n", $data) as $line) {
        if (preg_match('/^#\s*@missing:\s*([0-9A-F]+)\.\.([0-9A-F]+)\s*;\s*(\w+)/', $line, $m)) {
            $fn(hexdec($m[1]), hexdec($m[2]), $m[3]);
            continue;
        }
        $line = trim(explode('#', $line, 2)[0]);
        if ($line === '') {
            continue;
        }
        [$range, $value] = array_map('trim', explode(';', $line));
        $bounds = explode('..', $range);
        $fn(hexdec($bounds[0]), hexdec($bounds[1] ?? $bounds[0]), $value);
    }
}

// General_Category (for SA marks, Pi/Pf quotes, unassigned code points)
$gc = array_fill(0, MAX_CP + 1, 'Cn');
$first = null;
foreach (explode("\n", ucdFile('UnicodeData.txt', $version, $ucdDir)) as $line) {
    if ($line === '') {
        continue;
    }
    $f  = explode(';', $line);
    $cp = hexdec($f[0]);
    if (str_ends_with($f[1], 'First>')) {
        $first = $cp;
        continue;
    }
    for ($c = $first ?? $cp; $c <= $cp; $c++) {
        $gc[$c] = $f[2];
    }
    $first = null;
}

$lb = array_fill(0, MAX_CP + 1, 'XX');
eachRange(ucdFile('LineBreak.txt', $version, $ucdDir), function (int $a, int $b, string $v) use (&$lb) {
    for ($c = $a; $c <= $b; $c++) {
        $lb[$c] = $v;
    }
});

$eastAsian = array_fill(0, MAX_CP + 1, false);
eachRange(ucdFile('EastAsianWidth.txt', $version, $ucdDir), function (int $a, int $b, string $v) use (&$eastAsian) {
    for ($c = $a; $c <= $b; $c++) {
        $eastAsian[$c] = in_array($v, ['F', 'W', 'H'], true);
    }
});

$extPict = [];
eachRange(ucdFile('emoji/emoji-data.txt', $version, $ucdDir), function (int $a, int $b, string $v) use (&$extPict) {
    if ($v === 'Extended_Pictographic') {
        for ($c = $a; $c <= $b; $c++) {
            $extPict[$c] = true;
        }
    }
});

$classIds = array_flip(CLASSES);
$starts = [];
$values = [];
$prev   = -1;
for ($cp = 0; $cp <= MAX_CP; $cp++) {
    $cls = match ($lb[$cp]) {
        'AI', 'SG', 'XX' => 'AL',                                   // LB1
        'CJ'             => 'NS',                                   // LB1
        'SA'             => in_array($gc[$cp], ['Mn', 'Mc'], true) ? 'SM' : 'SA',
        'QU'             => match ($gc[$cp]) { 'Pi' => 'QI', 'Pf' => 'QF', default => 'QU' },
        default          => $lb[$cp],
    };
    $value = $classIds[$cls] ?? throw new RuntimeException(sprintf('Unknown class %s at U+%04X', $cls, $cp));
    if ($eastAsian[$cp]) {
        $value |= FLAG_EAST_ASIAN;
    }
    if (isset($extPict[$cp]) && $gc[$cp] === 'Cn') {
        $value |= FLAG_EXT_PICT_UNASSIGNED;
    }
    if ($value !== $prev) {
        $starts[] = $cp;
        $values[] = $value;
        $prev     = $value;
    }
}

$root  = dirname(__DIR__);
$count = count($starts);
$note  = "Generated by tools/generate-linebreak-data.php from Unicode $version. Do not edit.";

/** Format integers as wrapped lines of comma-separated literals. */
function rows(array $items, callable $fmt, string $indent, int $perLine = 12): string
{
    $lines = [];
    foreach (array_chunk($items, $perLine) as $chunk) {
        $lines[] = $indent . implode(', ', array_map($fmt, $chunk)) . ',';
    }
    return implode("\n", $lines);
}
$hex = fn(int $v) => sprintf('0x%X', $v);
$dec = fn(int $v) => (string) $v;
$classList = implode(' ', CLASSES);

$phpStarts = rows($starts, $hex, '        ');
$phpValues = rows($values, $dec, '        ', 24);
file_put_contents("$root/php/src/LineBreakData.php", <<<PHP
<?php

// $note

declare(strict_types=1);

namespace ThaiBreak;

/**
 * Unicode Line_Break property table (Unicode $version) for UAX #14.
 *
 * STARTS[i] is the first code point of a range whose packed value is VALUES[i].
 * Class ids: $classList
 *
 * @internal
 */
final class LineBreakData
{
    public const UNICODE_VERSION = '$version';

    public const STARTS = [
$phpStarts
    ];

    public const VALUES = [
$phpValues
    ];
}

PHP);

$goStarts = rows($starts, $hex, "\t");
$goValues = rows($values, $dec, "\t", 24);
file_put_contents("$root/go/linebreak_data.go", <<<GO
// Code generated by tools/generate-linebreak-data.php from Unicode $version. DO NOT EDIT.

package thaibreak

// lbUnicodeVersion is the Unicode version of the Line_Break table.
const lbUnicodeVersion = "$version"

// lbStarts[i] is the first code point of a range whose packed value is lbValues[i].
// Class ids: $classList
var lbStarts = [$count]uint32{
$goStarts
}

var lbValues = [$count]uint8{
$goValues
}

GO);

$rsStarts = rows($starts, $hex, '    ');
$rsValues = rows($values, $dec, '    ', 24);
file_put_contents("$root/rust/src/linebreak_data.rs", <<<RS
// $note

/// Unicode version of the Line_Break table.
pub const UNICODE_VERSION: &str = "$version";

/// `LB_STARTS[i]` is the first code point of a range whose packed value is `LB_VALUES[i]`.
/// Class ids: $classList
pub(crate) static LB_STARTS: [u32; $count] = [
$rsStarts
];

pub(crate) static LB_VALUES: [u8; $count] = [
$rsValues
];

RS);

$tsStarts = rows($starts, $hex, '  ');
$tsValues = rows($values, $dec, '  ', 24);
file_put_contents("$root/typescript/src/linebreak-data.ts", <<<TS
// $note

/** Unicode version of the Line_Break table. */
export const UNICODE_VERSION = '$version';

/**
 * LB_STARTS[i] is the first code point of a range whose packed value is LB_VALUES[i].
 * Class ids: $classList
 */
export const LB_STARTS = new Uint32Array([
$tsStarts
]);

export const LB_VALUES = new Uint8Array([
$tsValues
]);

TS);

fwrite(STDERR, "Wrote $count ranges for Unicode $version\n");
